[package]
name = "nh"
version = "3.4.14"
edition = "2021"
license = "EUPL-1.2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0", features = [
    "derive",
    "env",
    "unstable-styles",
    "color",
    "cargo",
] }
clap_complete = "4.0"
fern = { version = "0.6", features = [
    "colored",
] }
log = "0.4"
hostname = "^0.3"
clean-path = "0.2"
subprocess = "0.2"
dialoguer = { version = "0.10.2", default-features = false }
thiserror = "1.0"
derive_builder = "0.12.0"
tempfile = "3.5.0"
nix = { version = "0.26.2", default-features = false, features = [
    "user",
    "fs",
] }
anstyle = "1.0.0"
color-eyre = { version = "0.6.2", default-features = false, features = [
    "track-caller",
] }
ambassador = "0.3.5"
regex = "1.8.4"
once_cell = "1.18.0"
timeago = { version = "0.4.1", default-features = false }
humantime = "2.1.0"
serde_json = "1.0.100"
serde = { version = "1.0.166", features = ["derive"] }
